name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: '请填写docker镜像名称'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像名称

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
        docker system prune -a -f
        docker volume prune -f

    - name: Pull and Save Docker Image
      run: |
        image="${{ github.event.inputs.docker_image }}"
        echo "Pulling and saving image: $image"
        docker pull "${image}" --platform "linux/amd64"
        if [ $? -ne 0 ]; then
          echo "Failed to pull image: $image"
          exit 1
        fi
        filename="${image//\//_}-amd64.tar"
        docker save "${image}" -o "$filename"
        if [ $? -ne 0 ]; then
          echo "Failed to save image: $image"
          exit 1
        fi

    - name: Compress the TAR file
      run: |
        image="${{ github.event.inputs.docker_image }}"
        filename="${image//\//_}-amd64.tar"
        tar -czf x86-64-image.tar.gz "$filename"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-tar
        path: x86-64-image.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        image="${{ github.event.inputs.docker_image }}"
        filename="${image//\//_}-amd64.tar"
        rm "$filename"
